#pragma once
#include "GroundTransport.h"
#include "Camel.h"
#include "FastCamel.h"
#include "Centaur.h"
#include"Boots.h"
#include "AirTransport.h"
#include "FlyingCarpet.h"
#include "Eagle.h"
#include "Broom.h"
#include "Functions.h"